# Generated by Django 4.0.6 on 2022-09-30 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, upload_to='post/headers'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 12, 24, 35, 165636, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 12, 24, 35, 164649, tzinfo=utc)),
        ),
    ]
