# Generated by Django 4.0.6 on 2022-12-02 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_header_image_alter_comment_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 13, 40, 28, 638646, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 13, 40, 28, 637646, tzinfo=utc)),
        ),
    ]
