# Generated by Django 4.0.6 on 2022-12-02 14:54

import blog.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_created_date_alter_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 14, 54, 54, 210386, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 14, 54, 54, 209388, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, upload_to=blog.models.PathAndRename('post/headers')),
        ),
    ]
